### ISSUE TITLE
Implement change password

### ISSUE THREAD

**Issue by adelefelicia** [indykite/jarvis-sdk-python#43]
**Created by: Krisztian Marko Mar 15 2021 at 11:25 CET**
Updated: Jul 07 2021 at 09:28 CET
ClickUp ID: IK-708

**TODO in SDK**
- [x] Add change password by token method
- [x] Add change password by digital twin method
- [x] Add change password by token to api.py
- [x] Add change password by digital twin to api.py
- [x] Upload the new package to pypi

**Comment by adelefelicia** [comment]
Closed: Mar 30 2021 at 14:16 CET
